# GitHub Copilot configuration for EventCore
# This file configures how GitHub Copilot assists with code review and suggestions

review:
  # Focus areas for automated review
  focus_areas:
    - security
    - performance
    - type_safety
    - documentation
  
  # Custom instructions reference
  instructions_file: .github/copilot-instructions.md
  
  # Patterns to pay special attention to
  patterns:
    - name: "Type Safety"
      description: "Ensure nutype validation only at boundaries"
      files:
        - "**/*.rs"
      keywords:
        - "nutype"
        - "validate"
        - "parse"
    
    - name: "Security"
      description: "Check for security best practices"
      files:
        - "**/*.rs"
      keywords:
        - "unwrap"
        - "expect"
        - "panic"
        - "unsafe"
    
    - name: "Event Sourcing"
      description: "Verify event sourcing patterns"
      files:
        - "**/*.rs"
      keywords:
        - "Event"
        - "Command"
        - "Stream"
        - "Projection"