# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Enable version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates are always created immediately, regardless of schedule
    # They also ignore the open-pull-requests-limit
    allow:
      - dependency-type: "all"
    # Ignore internal workspace crates - these are versioned together
    ignore:
      - dependency-name: "eventcore"
      - dependency-name: "eventcore-postgres"
      - dependency-name: "eventcore-memory"
      - dependency-name: "eventcore-macros"
      - dependency-name: "eventcore-examples"
      - dependency-name: "eventcore-benchmarks"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    # Automatically merge non-breaking updates if CI passes
    # (Requires GitHub auto-merge to be enabled on the repository)
    assignees:
      - "jwilger"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "jwilger"