[alias]
# Run only unit tests (for pre-commit hook)
test-unit = "test --lib --bins"

# Run unit and integration tests (excludes performance tests)
test-ci = "test --workspace"

# Run performance tests explicitly
test-perf = "test --test performance_validation --test stress_tests -- --ignored"

# Run all tests including performance tests
test-all = "test --workspace -- --include-ignored"