# cargo-llvm-cov configuration

# Exclude test files and examples from coverage
[target.'cfg(all())']
exclude = [
    "eventcore-examples/**/*",
    "**/tests/**/*", 
    "**/benches/**/*",
]

# Include workspace members
workspace = true

# Generate both lcov and HTML reports
lcov = true
html = true

# Output directory for HTML reports
output-dir = "target/llvm-cov/html"