# cargo-nextest configuration
# https://nexte.st/book/configuration

[profile.default]
# Test retries for flaky tests
retries = { backoff = "fixed", count = 2, delay = "1s" }

# Fail fast on first test failure in CI
fail-fast = false

# Test output settings
failure-output = "immediate"
success-output = "never"
status-level = "pass"

# Test execution settings
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
# More verbose output in CI
failure-output = "immediate"
success-output = "final"
status-level = "all"

# No retries in CI to catch flaky tests
retries = 0

# Fail fast in CI
fail-fast = true

[test-groups]
# Define test groups for better organization
unit = { max-threads = 8 }
integration = { max-threads = 1 }  # Run integration tests sequentially to avoid database conflicts

# Automatically assign integration tests to the integration group
[[profile.default.overrides]]
filter = "test(~integration)"
test-group = "integration"

[[profile.default.overrides]]
filter = "package(eventcore-examples)"
test-group = "integration"