//! Procedural macros for the EventCore event sourcing library.
//!
//! This crate provides the `#[derive(Command)]` macro, which generates a
//! `CommandStreams` trait implementation for a command struct. The generated
//! implementation's `stream_declarations()` method returns every `StreamId`
//! field annotated with `#[stream]`, declaring the event streams that the
//! command reads and writes within a single atomic consistency boundary.
//!
//! # Usage
//!
//! Annotate a command struct with `#[derive(Command)]` and mark each
//! `StreamId` field that participates in the consistency boundary with
//! `#[stream]`:
//!
//! ```no_run
//! use eventcore::{Command, StreamId};
//!
//! #[derive(Command)]
//! pub struct TransferFunds {
//!     #[stream]
//!     pub source_account: StreamId,
//!     #[stream]
//!     pub destination_account: StreamId,
//!     pub amount: u64,
//! }
//! ```
//!
//! # Requirements
//!
//! - The derive target must be a struct with named fields (tuple structs are not
//!   supported).
//! - At least one field must carry the `#[stream]` attribute.
//! - Every `#[stream]`-annotated field must have type `StreamId` (or
//!   `eventcore::StreamId`).

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
#[cfg(feature = "experimental-modeling")]
use quote::format_ident;
use quote::quote;
use syn::{
    Data, DeriveInput, Error, Field, Fields, Meta, Path, Type, parse_macro_input,
    punctuated::Punctuated,
};
#[cfg(feature = "experimental-modeling")]
use syn::{
    Token,
    parse::{Parse, ParseStream},
};

/// Entry point for `#[derive(Command)]`.
///
/// Generates a `CommandStreams` implementation for the annotated struct. Every
/// `StreamId` field marked with `#[stream]` is
/// included in the generated `stream_declarations()` return value, establishing
/// the command's atomic consistency boundary.
///
/// See the [crate-level documentation](self) for requirements and a usage
/// example.
#[proc_macro_derive(Command, attributes(stream))]
pub fn command(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    match expand_command(&input) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

fn expand_command(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let ident = &input.ident;
    let fields = extract_named_fields(input)?;
    let stream_exprs = collect_stream_fields(fields)?;

    if stream_exprs.is_empty() {
        return Err(Error::new_spanned(
            ident,
            "EventCore: #[derive(Command)] requires at least one #[stream] StreamId field; add #[stream] to your StreamId member",
        ));
    }

    Ok(quote! {
        impl ::eventcore::CommandStreams for #ident {
            fn stream_declarations(&self) -> ::eventcore::StreamDeclarations {
                let mut streams = ::std::vec::Vec::new();
                for stream in [ #( #stream_exprs ),* ] {
                    if !streams.contains(&stream) {
                        streams.push(stream);
                    }
                }
                ::eventcore::StreamDeclarations::try_from_streams(streams)
                .expect("valid stream declarations generated by #[derive(Command)]")
            }
        }
    })
}

/// Ensures the derive target is a struct with named fields and returns them for
/// further validation.
fn extract_named_fields(input: &DeriveInput) -> syn::Result<&Punctuated<Field, syn::token::Comma>> {
    let Data::Struct(data_struct) = &input.data else {
        return Err(Error::new_spanned(
            &input.ident,
            "EventCore: #[derive(Command)] can only be applied to structs, not enums or unions",
        ));
    };

    let Fields::Named(fields) = &data_struct.fields else {
        return Err(Error::new_spanned(
            &input.ident,
            "EventCore: #[derive(Command)] requires named fields; tuple structs are not supported",
        ));
    };

    Ok(&fields.named)
}

/// Walks the struct fields, validating #[stream] usages and producing the
/// expressions used in the generated CommandStreams impl.
fn collect_stream_fields(
    fields: &Punctuated<Field, syn::token::Comma>,
) -> syn::Result<Vec<TokenStream2>> {
    let mut stream_exprs = Vec::new();

    for field in fields {
        if has_stream_marker(field)? {
            stream_exprs.push(stream_expression(field)?);
        }
    }

    Ok(stream_exprs)
}

/// Returns true when the field carries a valid #[stream] attribute.
fn has_stream_marker(field: &Field) -> syn::Result<bool> {
    let mut marked = false;

    for attr in &field.attrs {
        if attr.path().is_ident("stream") {
            if !matches!(&attr.meta, Meta::Path(_)) {
                return Err(Error::new_spanned(
                    attr,
                    "EventCore: #[stream] does not accept parameters",
                ));
            }

            marked = true;
        }
    }

    Ok(marked)
}

/// Produces the `self.field.clone()` expression for a validated stream field.
fn stream_expression(field: &Field) -> syn::Result<TokenStream2> {
    let Some(field_ident) = &field.ident else {
        return Err(Error::new_spanned(
            field,
            "EventCore: #[derive(Command)] requires named fields",
        ));
    };

    ensure_stream_id_type(field)?;

    Ok(quote! { self.#field_ident.clone() })
}

/// Confirms the field type resolves to StreamId (allowing qualified paths).
fn ensure_stream_id_type(field: &Field) -> syn::Result<()> {
    match &field.ty {
        Type::Path(type_path) if is_eventcore_stream_id(&type_path.path) => Ok(()),
        _ => Err(Error::new_spanned(
            field,
            "EventCore: #[stream] fields must have type eventcore::StreamId",
        )),
    }
}

fn is_eventcore_stream_id(path: &Path) -> bool {
    let Some(last) = path.segments.last() else {
        return false;
    };

    if last.ident != "StreamId" {
        return false;
    }

    path.segments
        .iter()
        .take(path.segments.len().saturating_sub(1))
        .all(|segment| {
            matches!(
                segment.ident.to_string().as_str(),
                "eventcore" | "crate" | "self" | "super"
            )
        })
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(StreamIdentity)]
pub fn stream_identity(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    match expand_stream_identity(&input) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

#[cfg(feature = "experimental-modeling")]
fn expand_stream_identity(input: &DeriveInput) -> syn::Result<TokenStream2> {
    if !input.generics.params.is_empty() {
        return Err(Error::new_spanned(
            &input.ident,
            "EventCore: #[derive(StreamIdentity)] does not support generic owners",
        ));
    }

    let access = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Unnamed(fields) if fields.unnamed.len() == 1 => quote! { &self.0 },
            Fields::Named(fields) if fields.named.len() == 1 => {
                let field = fields
                    .named
                    .first()
                    .and_then(|field| field.ident.as_ref())
                    .ok_or_else(|| {
                        Error::new_spanned(
                            fields,
                            "EventCore: expected a named stream identity field",
                        )
                    })?;
                quote! { &self.#field }
            }
            _ => {
                return Err(Error::new_spanned(
                    &input.ident,
                    "EventCore: #[derive(StreamIdentity)] requires a single-field newtype",
                ));
            }
        },
        _ => {
            return Err(Error::new_spanned(
                &input.ident,
                "EventCore: #[derive(StreamIdentity)] can only be applied to structs",
            ));
        }
    };
    let ident = &input.ident;

    Ok(quote! {
        impl ::eventcore::model::StreamIdentity for #ident {
            fn as_stream_id(&self) -> &::eventcore::StreamId {
                ::eventcore::model::StreamIdentity::as_stream_id(#access)
            }
        }
    })
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelInput, attributes(model, stream))]
pub fn model_input(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::Input)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelCommand, attributes(model, stream))]
pub fn model_command(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::Command)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelEvent, attributes(model))]
pub fn model_event(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::Event)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelState, attributes(model))]
pub fn model_state(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::State)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelReadModel, attributes(model))]
pub fn model_read_model(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::ReadModel)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelEffect, attributes(model))]
pub fn model_effect(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::Effect)
}

#[cfg(feature = "experimental-modeling")]
#[proc_macro_derive(ModelOutput, attributes(model))]
pub fn model_output(input: TokenStream) -> TokenStream {
    model_component(input, ModelComponentKind::Output)
}

#[cfg(feature = "experimental-modeling")]
#[derive(Clone, Copy)]
enum ModelComponentKind {
    Input,
    Command,
    Event,
    State,
    ReadModel,
    Effect,
    Output,
}

#[cfg(feature = "experimental-modeling")]
fn model_component(input: TokenStream, kind: ModelComponentKind) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    match expand_model_component(&input, kind) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

#[cfg(feature = "experimental-modeling")]
fn expand_model_component(
    input: &DeriveInput,
    kind: ModelComponentKind,
) -> syn::Result<TokenStream2> {
    if !input.generics.params.is_empty() {
        return Err(Error::new_spanned(
            &input.ident,
            "EventCore: modeled component owners cannot be generic in the experimental API",
        ));
    }

    let marker_trait = match kind {
        ModelComponentKind::Input => quote! { ::eventcore::model::ModelInput },
        ModelComponentKind::Command => quote! { ::eventcore::model::ModelCommand },
        ModelComponentKind::Event => quote! { ::eventcore::model::ModelEvent },
        ModelComponentKind::State => quote! { ::eventcore::model::ModelState },
        ModelComponentKind::ReadModel => quote! { ::eventcore::model::ModelReadModel },
        ModelComponentKind::Effect => quote! { ::eventcore::model::ModelEffect },
        ModelComponentKind::Output => quote! { ::eventcore::model::ModelOutput },
    };
    let ident = &input.ident;

    let Data::Struct(data) = &input.data else {
        if matches!(kind, ModelComponentKind::Event | ModelComponentKind::Effect) {
            return Ok(quote! { impl #marker_trait for #ident {} });
        }

        return Err(Error::new_spanned(
            ident,
            "EventCore: this modeled component derive requires a named struct",
        ));
    };
    let Fields::Named(named) = &data.fields else {
        return Err(Error::new_spanned(
            ident,
            "EventCore: modeled component builders require named fields; use a named payload struct for enum variants",
        ));
    };

    let fields: Vec<&Field> = named.named.iter().collect();
    let field_idents: Vec<_> = fields
        .iter()
        .map(|field| field.ident.clone().expect("named fields"))
        .collect();
    let field_types: Vec<_> = fields.iter().map(|field| &field.ty).collect();
    let state_idents: Vec<_> = field_idents
        .iter()
        .map(|field| format_ident!("{}State", pascal_case(field)))
        .collect();
    let marker_idents: Vec<_> = field_idents
        .iter()
        .map(|field| format_ident!("{}Field", pascal_case(field)))
        .collect();
    let module_ident = format_ident!("__eventcore_model_{}", ident.to_string().to_lowercase());
    let builder_ident = format_ident!("{}Builder", ident);
    let getter_idents: Vec<_> = field_idents
        .iter()
        .map(|field| format_ident!("__eventcore_model_get_{field}"))
        .collect();
    let value_idents: Vec<_> = field_idents
        .iter()
        .map(|field| format_ident!("__eventcore_model_value_{field}"))
        .collect();

    let field_markers = quote! {
        #[doc(hidden)]
        pub mod #module_ident {
            use super::*;

            #( pub struct #marker_idents; )*
            #( impl ::eventcore::model::ModelField for #marker_idents {
                type Value = #field_types;
            } )*
        }
    };

    let accessors = quote! {
        impl #ident {
            #( #[doc(hidden)]
            pub fn #getter_idents(&self) -> &#field_types {
                &self.#field_idents
            }

            #[doc(hidden)]
            pub fn #value_idents(
                value: #field_types,
            ) -> ::eventcore::model::FieldValue<#module_ident::#marker_idents> {
                ::eventcore::model::FieldValue::from_value(value)
            } )*
        }
    };

    let builder = expand_model_builder(ModelBuilderSpec {
        ident,
        builder_ident: &builder_ident,
        module_ident: &module_ident,
        field_idents: &field_idents,
        field_types: &field_types,
        state_idents: &state_idents,
        marker_idents: &marker_idents,
        accepts_raw_values: &fields
            .iter()
            .map(|field| {
                matches!(kind, ModelComponentKind::Input) && has_model_marker(field, "origin")
            })
            .collect::<Vec<_>>(),
        is_command: matches!(kind, ModelComponentKind::Command),
    });

    let state_initialization = if matches!(kind, ModelComponentKind::State) {
        let invalid = fields
            .iter()
            .find(|field| !has_model_marker(field, "default"));
        if let Some(field) = invalid {
            return Err(Error::new_spanned(
                field,
                "EventCore: #[derive(ModelState)] requires #[model(default)] on every field in this alpha API",
            ));
        }

        quote! {
            impl ::eventcore::model::ModelState for #ident {
                fn initial() -> ::eventcore::model::Modeled<Self> {
                    ::eventcore::model::Modeled::from_built(Self {
                        #( #field_idents: ::core::default::Default::default(), )*
                    })
                }
            }
        }
    } else {
        quote! {}
    };

    let role = match kind {
        ModelComponentKind::Input => "input",
        ModelComponentKind::Command => "command",
        ModelComponentKind::Event => "event",
        ModelComponentKind::State => "state",
        ModelComponentKind::ReadModel => "read_model",
        ModelComponentKind::Effect => "effect",
        ModelComponentKind::Output => "output",
    };
    let roots: Vec<_> = fields
        .iter()
        .map(|field| {
            matches!(kind, ModelComponentKind::Input) && has_model_marker(field, "origin")
                || (matches!(kind, ModelComponentKind::State) && has_model_marker(field, "default"))
        })
        .collect();
    let registration = quote! {
        #( ::eventcore::__eventcore_register_model_descriptor!(
            field,
            #role,
            stringify!(#ident),
            stringify!(#field_idents),
            #roots,
        ); )*
    };

    let streams = if matches!(kind, ModelComponentKind::Command) {
        let stream_fields: Vec<_> = fields
            .iter()
            .filter(|field| has_stream_marker(field).unwrap_or(false))
            .map(|field| field.ident.clone().expect("named fields"))
            .collect();
        if stream_fields.is_empty() {
            return Err(Error::new_spanned(
                ident,
                "EventCore: #[derive(ModelCommand)] requires at least one #[stream] semantic stream field",
            ));
        }
        quote! {
            impl ::eventcore::CommandStreams for #ident {
                fn stream_declarations(&self) -> ::eventcore::StreamDeclarations {
                    let mut streams = ::std::vec::Vec::new();
                    #( {
                        let stream = ::eventcore::model::StreamIdentity::as_stream_id(&self.#stream_fields).clone();
                        if !streams.contains(&stream) {
                            streams.push(stream);
                        }
                    } )*
                    ::eventcore::StreamDeclarations::try_from_streams(streams)
                        .expect("modeled command derives at least one stream")
                }
            }
        }
    } else {
        quote! {}
    };

    let marker_impl = if matches!(kind, ModelComponentKind::State) {
        quote! {}
    } else {
        quote! { impl #marker_trait for #ident {} }
    };

    Ok(quote! {
        #marker_impl
        #field_markers
        #accessors
        #builder
        #state_initialization
        #streams
        #registration
    })
}

#[cfg(feature = "experimental-modeling")]
struct ModelBuilderSpec<'a> {
    ident: &'a syn::Ident,
    builder_ident: &'a syn::Ident,
    module_ident: &'a syn::Ident,
    field_idents: &'a [syn::Ident],
    field_types: &'a [&'a Type],
    state_idents: &'a [syn::Ident],
    marker_idents: &'a [syn::Ident],
    accepts_raw_values: &'a [bool],
    is_command: bool,
}

#[cfg(feature = "experimental-modeling")]
fn expand_model_builder(spec: ModelBuilderSpec<'_>) -> TokenStream2 {
    let ModelBuilderSpec {
        ident,
        builder_ident,
        module_ident,
        field_idents,
        field_types,
        state_idents,
        marker_idents,
        accepts_raw_values,
        is_command,
    } = spec;
    let initial_states = field_idents
        .iter()
        .map(|_| quote! { ::eventcore::model::Unset });
    let initial_values = field_idents
        .iter()
        .map(|field| quote! { #field: ::eventcore::model::Unset });

    let setters = field_idents.iter().enumerate().map(|(index, field)| {
        let others: Vec<_> = state_idents
            .iter()
            .enumerate()
            .filter_map(|(other_index, state)| (other_index != index).then_some(state))
            .collect();
        let input_states = state_idents.iter().enumerate().map(|(other_index, state)| {
            if other_index == index {
                quote! { ::eventcore::model::Unset }
            } else {
                quote! { #state }
            }
        });
        let output_states = state_idents.iter().enumerate().map(|(other_index, state)| {
            if other_index == index {
                let marker = &marker_idents[index];
                quote! { ::eventcore::model::Set<::eventcore::model::FieldValue<#module_ident::#marker>> }
            } else {
                quote! { #state }
            }
        });
        let output_values = field_idents.iter().enumerate().map(|(other_index, other_field)| {
            if other_index == index {
                if accepts_raw_values[index] {
                    quote! { #other_field: ::eventcore::model::Set::new(::eventcore::model::FieldValue::from_value(value)) }
                } else {
                    quote! { #other_field: ::eventcore::model::Set::new(value.into_field_value()) }
                }
            } else {
                quote! { #other_field: self.#other_field }
            }
        });
        let marker = &marker_idents[index];
        let field_type = field_types[index];
        let argument = if accepts_raw_values[index] {
            quote! { value: #field_type }
        } else {
            quote! { value: impl ::eventcore::model::IntoFieldValue<#module_ident::#marker> }
        };

        quote! {
            impl<#(#others),*> #builder_ident<#(#input_states),*> {
                pub fn #field(self, #argument) -> #builder_ident<#(#output_states),*> {
                    #builder_ident {
                        #( #output_values, )*
                    }
                }
            }
        }
    });
    let set_states = marker_idents.iter().map(|marker| {
        quote! { ::eventcore::model::Set<::eventcore::model::FieldValue<#module_ident::#marker>> }
    });
    let built_fields = field_idents.iter().map(|field| {
        quote! { #field: self.#field.into_inner().into_inner() }
    });
    let finish = if is_command {
        quote! { ::eventcore::model::ModeledCommand::from_built(#ident { #( #built_fields, )* }) }
    } else {
        quote! { ::eventcore::model::Modeled::from_built(#ident { #( #built_fields, )* }) }
    };
    let output = if is_command {
        quote! { ::eventcore::model::ModeledCommand<#ident> }
    } else {
        quote! { ::eventcore::model::Modeled<#ident> }
    };

    quote! {
        #[doc(hidden)]
        pub struct #builder_ident<#(#state_idents = ::eventcore::model::Unset),*> {
            #( #field_idents: #state_idents, )*
        }

        impl #ident {
            #[must_use]
            pub fn model_builder() -> #builder_ident<#(#initial_states),*> {
                #builder_ident {
                    #( #initial_values, )*
                }
            }
        }

        #( #setters )*

        impl #builder_ident<#(#set_states),*> {
            #[must_use]
            pub fn build(self) -> #output {
                #finish
            }
        }
    }
}

#[cfg(feature = "experimental-modeling")]
fn pascal_case(ident: &syn::Ident) -> syn::Ident {
    let mut value = String::new();
    for segment in ident.to_string().split('_') {
        let mut characters = segment.chars();
        if let Some(first) = characters.next() {
            value.extend(first.to_uppercase());
            value.extend(characters);
        }
    }
    format_ident!("{value}")
}

#[cfg(feature = "experimental-modeling")]
fn has_model_marker(field: &Field, expected: &str) -> bool {
    field.attrs.iter().any(|attribute| {
        attribute.path().is_ident("model")
            && attribute
                .parse_args::<syn::Ident>()
                .is_ok_and(|marker| marker == expected)
    })
}

/// Defines one executable field-to-field mapping for the experimental modeled
/// lane. The mapping implementation is used both by runtime builders and, when
/// enabled, the information-completeness checker.
#[cfg(feature = "experimental-modeling")]
#[proc_macro]
pub fn mapping(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as MappingDefinition);

    match expand_mapping(&input) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

#[cfg(feature = "experimental-modeling")]
struct MappingDefinition {
    name: syn::Ident,
    sources: Vec<MappingField>,
    target: MappingField,
    transform: MappingTransform,
}

#[cfg(feature = "experimental-modeling")]
struct MappingField {
    owner: Path,
    field: syn::Ident,
    previous: bool,
}

#[cfg(feature = "experimental-modeling")]
enum MappingTransform {
    Clone,
    Copy,
    Function(Path),
    Fallible { function: Path, error: Box<Type> },
}

#[cfg(feature = "experimental-modeling")]
impl Parse for MappingDefinition {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let name = input.parse()?;
        let _ = input.parse::<Token![:]>()?;
        let sources = if input.peek(syn::token::Paren) {
            let content;
            syn::parenthesized!(content in input);
            Punctuated::<MappingField, Token![,]>::parse_terminated(&content)?
                .into_iter()
                .collect()
        } else {
            vec![input.parse()?]
        };
        let _ = input.parse::<Token![=>]>()?;
        let target = input.parse()?;
        let using: syn::Ident = input.parse()?;
        if using != "using" {
            return Err(Error::new_spanned(using, "EventCore: expected `using`"));
        }

        let transform = if input.peek(Token![try]) {
            let _ = input.parse::<Token![try]>()?;
            let function = input.parse()?;
            let _ = input.parse::<Token![,]>()?;
            let error_name: syn::Ident = input.parse()?;
            if error_name != "error" {
                return Err(Error::new_spanned(
                    error_name,
                    "EventCore: expected `error = ErrorType`",
                ));
            }
            let _ = input.parse::<Token![=]>()?;
            let error = Box::new(input.parse()?);
            MappingTransform::Fallible { function, error }
        } else {
            let function: Path = input.parse()?;
            let name = function
                .segments
                .last()
                .map(|segment| segment.ident.to_string())
                .unwrap_or_default();
            match name.as_str() {
                "clone" => MappingTransform::Clone,
                "copy" => MappingTransform::Copy,
                _ => MappingTransform::Function(function),
            }
        };
        let _ = input.parse::<Token![;]>()?;

        if sources.is_empty() {
            return Err(Error::new_spanned(
                name,
                "EventCore: mappings require at least one source field",
            ));
        }

        Ok(Self {
            name,
            sources,
            target,
            transform,
        })
    }
}

#[cfg(feature = "experimental-modeling")]
impl Parse for MappingField {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let previous = if input.peek(syn::Ident) && input.peek2(syn::token::Paren) {
            let marker: syn::Ident = input.parse()?;
            if marker != "previous" {
                return Err(Error::new_spanned(
                    marker,
                    "EventCore: expected `previous(...)`",
                ));
            }
            let content;
            syn::parenthesized!(content in input);
            let field: MappingField = content.parse()?;
            if !content.is_empty() {
                return Err(Error::new(
                    field.field.span(),
                    "EventCore: invalid previous field reference",
                ));
            }
            return Ok(Self {
                previous: true,
                ..field
            });
        } else {
            false
        };
        let owner = input.parse()?;
        let _ = input.parse::<Token![.]>()?;
        let field = input.parse()?;
        Ok(Self {
            owner,
            field,
            previous,
        })
    }
}

#[cfg(feature = "experimental-modeling")]
fn expand_mapping(definition: &MappingDefinition) -> syn::Result<TokenStream2> {
    let name = &definition.name;
    let target_marker = model_field_marker_path(&definition.target)?;
    let target_owner = &definition.target.owner;
    let target_value = format_ident!("__eventcore_model_value_{}", definition.target.field);
    let target_field = &definition.target.field;
    let source_types: Vec<_> = definition
        .sources
        .iter()
        .map(|source| &source.owner)
        .collect();
    let source_labels: Vec<_> = definition
        .sources
        .iter()
        .map(|source| {
            let owner = &source.owner;
            let field = &source.field;
            quote! { concat!(stringify!(#owner), ".", stringify!(#field)) }
        })
        .collect();
    let temporal_sources: Vec<_> = definition
        .sources
        .iter()
        .map(|source| source.previous)
        .collect();
    let source_idents: Vec<_> = (0..definition.sources.len())
        .map(|index| format_ident!("source_{index}"))
        .collect();
    let source_values: Vec<_> = definition
        .sources
        .iter()
        .zip(&source_idents)
        .map(|(source, source_ident)| {
            let owner = &source.owner;
            let getter = format_ident!("__eventcore_model_get_{}", source.field);
            quote! { #owner::#getter(#source_ident) }
        })
        .collect();
    let call_arguments = source_values.iter();

    let transform = match &definition.transform {
        MappingTransform::Clone if source_values.len() == 1 => {
            let source = &source_values[0];
            quote! { #source.clone() }
        }
        MappingTransform::Copy if source_values.len() == 1 => {
            let source = &source_values[0];
            quote! { *#source }
        }
        MappingTransform::Function(function) => quote! { #function(#(#call_arguments),*) },
        MappingTransform::Fallible { function, error } => {
            let arguments = source_values.iter();
            let signature = mapping_signature(&source_idents, &source_types);
            return Ok(quote! {
                pub struct #name;

                impl #name {
                    pub fn apply(#signature) -> ::core::result::Result<::eventcore::model::FieldValue<#target_marker>, #error> {
                        #function(#(#arguments),*) .map(#target_owner::#target_value)
                    }
                }

                ::eventcore::__eventcore_register_model_descriptor!(
                    mapping,
                    stringify!(#name),
                    &[#(#source_labels),*],
                    concat!(stringify!(#target_owner), ".", stringify!(#target_field)),
                    &[#(#temporal_sources),*],
                );
            });
        }
        MappingTransform::Clone | MappingTransform::Copy => {
            return Err(Error::new_spanned(
                name,
                "EventCore: `using clone` and `using copy` require exactly one source field",
            ));
        }
    };
    let signature = mapping_signature(&source_idents, &source_types);

    Ok(quote! {
        pub struct #name;

        impl #name {
            pub fn apply(#signature) -> ::eventcore::model::FieldValue<#target_marker> {
                #target_owner::#target_value(#transform)
            }
        }

        ::eventcore::__eventcore_register_model_descriptor!(
            mapping,
            stringify!(#name),
            &[#(#source_labels),*],
            concat!(stringify!(#target_owner), ".", stringify!(#target_field)),
            &[#(#temporal_sources),*],
        );
    })
}

#[cfg(feature = "experimental-modeling")]
fn mapping_signature(source_idents: &[syn::Ident], source_types: &[&Path]) -> TokenStream2 {
    if source_idents.len() == 1 {
        let source = &source_idents[0];
        let source_type = source_types[0];
        quote! { #source: &#source_type }
    } else {
        quote! { (#(#source_idents),*): (#(&#source_types),*) }
    }
}

#[cfg(feature = "experimental-modeling")]
fn model_field_marker_path(field: &MappingField) -> syn::Result<TokenStream2> {
    let mut owner = field.owner.clone();
    let Some(last) = owner.segments.last_mut() else {
        return Err(Error::new_spanned(
            &field.owner,
            "EventCore: mapping owner path is empty",
        ));
    };
    last.ident = format_ident!(
        "__eventcore_model_{}",
        last.ident.to_string().to_lowercase()
    );
    let marker = format_ident!("{}Field", pascal_case(&field.field));
    Ok(quote! { #owner::#marker })
}
