name: Deploy Website

on:
  # Allow manual deployment for testing
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdBook
        run: |
          MDBOOK_VERSION="0.4.40"
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv mdbook /usr/local/bin/

      - name: Build API documentation
        run: |
          cargo doc --no-deps --workspace
          # Copy to website output
          mkdir -p website/target/website/api
          cp -r target/doc/* website/target/website/api/

      - name: Sync documentation
        run: |
          cd website
          chmod +x sync-docs.sh
          ./sync-docs.sh

      - name: Build website
        run: |
          cd website
          mdbook build


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/target/website

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4